apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mongo-depl
  labels:
    app: spring-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mongo
  template:
    metadata:
      labels:
        app: spring-mongo
    spec:
      containers:
      - name: spring-mongo
        image: khushi1701/spring-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1000
        env:
        - name: DB_URL
          value: mongo
        - name: DB_USERNAME
          value: mongoadmin 
        - name: DB_PASSWORD
          value: secret 
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mongo-svc
spec:
  type: NodePort
  selector:
    app: spring-mongo
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 1000